-- 코드를 입력하세요
SELECT 
    AUTHOR.AUTHOR_ID, 
    AUTHOR.AUTHOR_NAME, 
    BOOK.CATEGORY, 
    SUM(S.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM AUTHOR
JOIN BOOK ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
JOIN BOOK_SALES S ON BOOK.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE "2022-01%"
GROUP BY AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME , BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC;