-- 코드를 입력하세요
SELECT P.PRODUCT_CODE AS PRODUCT_CODE,
        SUM(SALES_AMOUNT) * PRICE AS SALES
FROM PRODUCT  P 
JOIN OFFLINE_SALE S
ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;