-- 코드를 입력하세요
SELECT UGU.USER_ID,UGU.NICKNAME,
CONCAT(CITY," ",STREET_ADDRESS1," ",STREET_ADDRESS2) AS "전체주소",
CONCAT(LEFT(TLNO,3),"-", SUBSTRING(TLNO,4,4),"-",RIGHT(TLNO,4)) "전화번호"
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(*)>=3
ORDER BY USER_ID DESC;