-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR , MONTH(SALES_DATE) MONTH, I.GENDER GENDER, COUNT(DISTINCT(I.USER_ID)) USERS
FROM USER_INFO I 
JOIN ONLINE_SALE S
ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), I.GENDER
ORDER BY YEAR, MONTH, GENDER, USERS