-- 코드를 입력하세요
SELECT 
    H.CAR_ID,
    CASE
        WHEN K.CAR_ID IS NULL THEN '대여 가능'
        ELSE '대여중'
        END AS AVAILABILITY

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT  JOIN (SELECT DISTINCT CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16') K 
ON H.CAR_ID = K.CAR_ID
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC;