SELECT 
    C.HISTORY_ID, 
    FLOOR(CASE 
        WHEN C.DATE_DIFF >= 90 THEN A.DAILY_FEE * 0.85 * C.DATE_DIFF -- 
        WHEN C.DATE_DIFF >= 30 THEN A.DAILY_FEE * 0.92 * C.DATE_DIFF -- 
        WHEN C.DATE_DIFF >= 7  THEN A.DAILY_FEE * 0.95 * C.DATE_DIFF -- 
        ELSE A.DAILY_FEE * C.DATE_DIFF
    END) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A 
JOIN 
    (
        SELECT 
            H.HISTORY_ID, 
            H.CAR_ID, 
            DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DATE_DIFF
        FROM CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
        WHERE C.CAR_TYPE = '트럭'
    ) C ON A.CAR_ID = C.CAR_ID
-- 프로그래머스 최종 정답 처리를 위한 정렬 조건 추가
ORDER BY FEE DESC, HISTORY_ID DESC;
