-- 코드를 입력하세요
SELECT HALF.FLAVOR
FROM FIRST_HALF HALF
JOIN 
(SELECT F.SHIPMENT_ID, F.TOTAL_ORDER + S.TOTAL_ORDER AS SUMS, F.FLAVOR
FROM FIRST_HALF F
JOIN (SELECT SHIPMENT_ID , FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM JULY 
GROUP BY FLAVOR)  S
ON F.SHIPMENT_ID = S.SHIPMENT_ID) FRU
ON HALF.SHIPMENT_ID = FRU.SHIPMENT_ID
ORDER BY FRU.SUMS DESC LIMIT 3;
