-- 코드를 입력하세요
SELECT AP.APNT_NO,  PA.PT_NAME, PA.PT_NO,AP.MCDP_CD,DO.DR_NAME,AP.APNT_YMD
FROM PATIENT PA 
JOIN APPOINTMENT AP
ON PA.PT_NO = AP.PT_NO
JOIN DOCTOR DO
ON DO.DR_ID = AP.MDDR_ID
WHERE AP.APNT_YMD LIKE "2022-04-13%" 
AND AP.APNT_CNCL_YN = 'N'
AND AP.MCDP_cD = 'CS'
ORDER BY AP.APNT_YMD ASC