-- 코드를 입력하세요
SELECT T.APNT_NO AS "APNT_NO",
P.PT_NAME AS "PT_NAME",
T.PT_NO AS "PT_NO",
T.MCDP_CD AS "MCDP_CD",
D.DR_NAME AS "DR_NAME",
T.APNT_YMD AS "APNT_YMD"
FROM DOCTOR D
JOIN APPOINTMENT T
ON D.DR_ID = T.MDDR_ID
JOIN PATIENT P
ON P.PT_NO = T.PT_NO
WHERE T.APNT_YMD LIKE "2022-04-13%" AND APNT_CNCL_YN = "N" AND T.MCDP_CD = "CS"
ORDER BY APNT_YMD ASC;