-- 코드를 작성해주세요
SELECT EM.EMP_NO, EM.EMP_NAME,
    T.GRADE,
    CASE 
        WHEN T.GRADE = "S" THEN T.SAL * 0.2
        WHEN T.GRADE = "A" THEN T.SAL * 0.15
        WHEN T.GRADE = "B" THEN T.SAL * 0.1
        ELSE 0
        END AS "BONUS"
FROM HR_EMPLOYEES  EM
JOIN
(SELECT E.EMP_NAME, E.EMP_NO,
    CASE 
        WHEN G.SCORE>=96 THEN "S"
        WHEN G.SCORE>=90 THEN "A"
        WHEN G.SCORE>=80 THEN "B"
        ELSE "C"
        END AS "GRADE",
    E.SAL AS SAL
FROM HR_DEPARTMENT D 
JOIN HR_EMPLOYEES E 
ON D.DEPT_ID = E.DEPT_ID
JOIN (SELECT EMP_NO,YEAR,AVG(SCORE) SCORE
FROM HR_GRADE
GROUP BY EMP_NO) G
ON E.EMP_NO = G.EMP_NO) T
ON EM.EMP_NO = T.EMP_NO
ORDER BY EM.EMP_NO ASC;