-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) YEAR,
    (S.SIZE_OF_COLONY - D.SIZE_OF_COLONY) YEAR_DEV,
ID
FROM ECOLI_DATA D
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,MAX(SIZE_OF_COLONY) SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) AS S
ON YEAR(D.DIFFERENTIATION_DATE) = S.YEAR
ORDER BY YEAR,YEAR_DEV;