-- 코드를 입력하세요
SELECT DISTINCT (CAR.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON CAR.CAR_ID = RH.CAR_ID
WHERE RH.START_DATE LIKE "2022-10%" AND CAR.CAR_TYPE ="세단"
ORDER BY CAR_ID DESC;