-- 코드를 작성해주세요
SELECT SUM(H3.SCORE), H3.EMP_NO, H2.EMP_NAME, H2.POSITION, H2.EMAIL
FROM HR_DEPARTMENT H1
JOIN HR_EMPLOYEES H2
ON H1.DEPT_ID = H2.DEPT_ID
JOIN HR_GRADE H3
ON H2.EMP_NO = H3.EMP_NO
WHERE YEAR = '2022'
GROUP BY H3.EMP_NO 
ORDER BY SUM(H3.SCORE) DESC LIMIT 1;