-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",BOARD.BOARD_ID,"/",FILE.FILE_ID,FILE.FILE_NAME,FILE.FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE FILE
JOIN (SELECT * FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) BOARD
ON FILE.BOARD_ID = BOARD.BOARD_ID 
ORDER BY FILE.FILE_ID DESC;

