-- 코드를 입력하세요
SELECT P1.CATEGORY, P2.MAX_PRICE, P1.PRODUCT_NAME
FROM FOOD_PRODUCT P1
JOIN(SELECT MAX(PRICE) MAX_PRICE, CATEGORY
FROM FOOD_PRODUCT
WHERE CATEGORY IN ("식용유","과자","국","김치")
GROUP BY CATEGORY    ) P2
ON P1.CATEGORY = P2.CATEGORY
AND P1.PRICE = P2.MAX_PRICE
ORDER BY P2.MAX_PRICE DESC
