-- 코드를 입력하세요
SELECT FP1.CATEGORY AS CATEGORY, FP1.PRICE, FP1.PRODUCT_NAME
FROM FOOD_PRODUCT FP1
JOIN 
    (SELECT CATEGORY, MAX(PRICE) PRICE
    FROM FOOD_PRODUCT 
    WHERE CATEGORY = "과자" OR CATEGORY = "식용유"
    OR CATEGORY = "국" OR CATEGORY = "김치"
    GROUP BY CATEGORY
    ) AS FP2
ON FP1.CATEGORY = FP2.CATEGORY
WHERE FP2.PRICE = FP1.PRICE
ORDER BY FP1.PRICE DESC;